export const employees = [
  {
    id: "E001",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    department: "Engineering",
    Role: "Software Engineer",
    Type: "Full-Time",
    Active: "Active",
    ReportingTo: "Manager A",
    JoiningDate: "2022-01-15",
    BirthDate: "1990-05-20",
  },
  {
    id: "E002",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "HR",
    Role: "HR Manager",
    Type: "Part-Time",
    Active: "Inactive",
    ReportingTo: "Director B",
    JoiningDate: "2020-06-10",
    BirthDate: "1985-11-30",
  },
  {
    id: "E003",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "HR",
    Role: "HR Manager",
    Type: "Part-Time",
    Active: "Inactive",
    ReportingTo: "Director B",
    JoiningDate: "2020-06-10",
    BirthDate: "1985-11-30",
  },
  {
    id: "E004",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "HR",
    Role: "HR Manager",
    Type: "Part-Time",
    Active: "Inactive",
    ReportingTo: "Director B",
    JoiningDate: "2020-06-10",
    BirthDate: "1985-11-30",
  },
  {
    id: "E005",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "HR",
    Role: "HR Manager",
    Type: "Part-Time",
    Active: "Inactive",
    ReportingTo: "Director B",
    JoiningDate: "2020-06-10",
    BirthDate: "1985-11-30",
  },
  {
    id: "E006",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "HR",
    Role: "HR Manager",
    Type: "Part-Time",
    Active: "Inactive",
    ReportingTo: "Director B",
    JoiningDate: "2020-06-10",
    BirthDate: "1985-11-30",
  },
  {
    id: "E007",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "HR",
    Role: "HR Manager",
    Type: "Part-Time",
    Active: "Inactive",
    ReportingTo: "Director B",
    JoiningDate: "2020-06-10",
    BirthDate: "1985-11-30",
  },
  {
    id: "E008",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "HR",
    Role: "HR Manager",
    Type: "Part-Time",
    Active: "Inactive",
    ReportingTo: "Director B",
    JoiningDate: "2020-06-10",
    BirthDate: "1985-11-30",
  },
  {
    id: "E009",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "HR",
    Role: "HR Manager",
    Type: "Part-Time",
    Active: "Inactive",
    ReportingTo: "Director B",
    JoiningDate: "2020-06-10",
    BirthDate: "1985-11-30",
  },
  {
    id: "E010",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "HR",
    Role: "HR Manager",
    Type: "Part-Time",
    Active: "Inactive",
    ReportingTo: "Director B",
    JoiningDate: "2020-06-10",
    BirthDate: "1985-11-30",
  },
  {
    id: "E011",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "HR",
    Role: "HR Manager",
    Type: "Part-Time",
    Active: "Inactive",
    ReportingTo: "Director B",
    JoiningDate: "2020-06-10",
    BirthDate: "1985-11-30",
  },
  {
    id: "E012",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "HR",
    Role: "HR Manager",
    Type: "Part-Time",
    Active: "Inactive",
    ReportingTo: "Director B",
    JoiningDate: "2020-06-10",
    BirthDate: "1985-11-30",
  },
  {
    id: "E013",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    department: "HR",
    Role: "HR Manager",
    Type: "Part-Time",
    Active: "Inactive",
    ReportingTo: "Director B",
    JoiningDate: "2020-06-10",
    BirthDate: "1985-11-30",
  },
  // Add more employee records as needed
];